### ISSUE TITLE
[Feature] Migrate command for multi tenancy

### ISSUE THREAD

**Issue by Inoir** [adrien2p/medusa-extender#100]
**Is your feature request related to a problem? Please describe.**
Currently the migrate command is only respecting the projectConfig database. If youre using multi tenancy, this is kinda shitty, cause you need to migrate every tenant database manually. For this you need to change projectConfig manually to every tenant.
if youve alot tenants, this is painful as f....

**Describe the solution you'd like**
Make the migration command also possible for multi_tenancy settings

**Describe alternatives you've considered**
There is none. If the config defines an enabled multi_tenancy, migration should run everywhere, maybe with flag

**Additional context**
Please? :)

**Comment by adrien2p** [comment]
Hey there, it is a good suggestion, i ll add the support as soon as I can. otherwise, feel free to open a pr and i will be glad to review it 🚀

**Comment by adrien2p** [comment]
Hey @Inoir , sorry, didn't get the time yet to do iut, but I do not forget about it 🚀

**Comment by adrien2p** [comment]
@Inoir Hey there, Finally got the job done myself :) I just need to update the documentation and it will be merged

**Comment by Inoir** [comment]
Question back here, i just looked over your changes, cause i tried to implement it also and got stuck with creating the database. is this also included in your solution? if so can you point me to the direction i dont see the lines? i got it only working with custom sql command. so i didnt like my solution.

**Comment by adrien2p** [comment]
The database creation is separate from the project. When setting up your configuration, it is implicitly supposed that the DB already exists. Here is a command https://www.postgresql.org/docs/current/app-createdb.html#:~:text=createdb%20creates%20a%20new%20PostgreSQL,the%20SQL%20command%20CREATE%20DATABASE%20.

**Comment by adrien2p** [comment]
If your use case is that the tenants are created dynamically, then having them referenced statically in the config might not be enough. At the moment, for each new tenant conf, you have to update your env and the config file and then re start the app. Unfortunately, we opted for that solution for a security issue about storing the creds in the db which we want to avoid. If you have any idea on how to allow that without a security issue while allowing to still use the existing, you are welcome to propose a pr 🙌

**Comment by Inoir** [comment]
ah nice yes our current solution takes secrets from env. kinda same as the tenant resolver you can already define in the config, we have an db resolver, does the same, gives the env vars for db connection back. so you kinda need to define for every tenant env vars `TENANT_XXXX_DB_PASSWORD` ie

Thanks for clarification, helps a lot.
Nice work btw!

**Comment by adrien2p** [comment]
Thanks a lot for the kind words. Hope that the module will help you 👍
