### ISSUE TITLE
[BUG] Init command

### ISSUE THREAD

**Issue by williamtran29** [adrien2p/medusa-extender#112]
**To Reproduce**
Run command: medex init

**Screenshots**
<img width="890" alt="Screen Shot 2022-08-14 at 03 14 29" src="https://user-images.githubusercontent.com/9301504/184509435-07de844d-62fe-4fb3-bdf8-cbdba3256536.png">

**Package version:**
   "@medusajs/medusa": "^1.3.4",
   "@medusajs/medusa-cli": "^1.3.1",
   "medusa-extender": "^1.7.4",

**Comment by adrien2p** [comment]
Thanks for reporting it. Can i get you to open a pr please or do you prefer that i ll do it? ☺️

**Comment by adrien2p** [comment]
Just to be sure could you share me your tsconfig please?

**Comment by williamtran29** [comment]
Look like this is a bug from medusa CLI itself
<img width="1701" alt="Screen Shot 2022-08-15 at 13 47 19" src="https://user-images.githubusercontent.com/9301504/184589024-f73fdbf8-8e42-4a00-9eb3-e9fe9f8bc419.png">
After I remove "," on line 4, it works fine
