### ISSUE TITLE
Extending product entity

### ISSUE THREAD

**Issue by pelonidas** [adrien2p/medusa-extender#121]
Hi, I have a question about extension of Product entity. I extended the product entity with one more field I checked the database and the field was successfully added. My question is how can I access the extended product service? I defined custom route where I tried to use productService through the scope but I didn't see my extended column. Can you help me with that? thanks in advance

**Comment by adrien2p** [comment]
If you did not create an a product service that extend the existing one then there is no extended product service. Could you tell me a bit more about that custom end point and what it is for? So that i can provide you the best approach depending on your answer

**Comment by pelonidas** [comment]
Hello, I am trying to extend the current product Entity. I am using typescript and when I try to use extended product in req.scope.create I don't see the newly created column

**Comment by adrien2p** [comment]
You need to extend the validator AdminPostProductsReq to accept your property, so that when you send the payload you can send that value to to be added during the product creation.

**Comment by pelonidas** [comment]
Thanks, will try it. One more question if I have any other question can I contact you somewhere else besides here? Thanks again

**Comment by adrien2p** [comment]
Yes, you can ask them on discord as well. Other persons are using the extender and i am a core member of medusa too 👍
