### ISSUE TITLE
Service Type Error

### ISSUE THREAD

**Issue by itzomen** [adrien2p/medusa-extender#122]
**Describe the bug**
I keep getting type errors when I create a custom service.  This happens when `import { StoreService as MedusaStoreService } from "@medusajs/medusa/dist/services";`. Seems like the types exist on medusa-interfaces because importing `import { BaseService as MedusaStoreService } from "medusa-interfaces";` get rid of the errors

**To Reproduce**
1. Follow the [Create Marketplace Tutorial part 1](https://dev.to/medusajs/create-an-open-source-commerce-marketplace-part-1-3m5k)
2. The store.service and user.service throws the following errors

**Expected behavior**
Normally, we should not get any type Error, except I am doing something wrong

**Screenshots**
###
![Screenshot from 2022-08-21 15-38-03](https://user-images.githubusercontent.com/61752841/185797012-fd405a2b-c857-4b3f-ba8d-fc13ca4a20b6.png)
###
![Screenshot from 2022-08-21 15-38-28](https://user-images.githubusercontent.com/61752841/185797022-2375222f-f184-4555-9953-7b4de99494c6.png)

###
![Screenshot from 2022-08-21 15-38-39](https://user-images.githubusercontent.com/61752841/185797039-f82dfebc-1191-4686-ba98-e767c8547764.png)

**Package version:**
 - Version 1.7.4

**Additional context**
```json
# medusa versions
"@medusajs/medusa": "^1.3.5",
"@medusajs/medusa-cli": "^1.3.1",
```

**Comment by adrien2p** [comment]
In the newest version of medusa, the service extends the TransactionBaseService and not the baseService. So you don't need to implement the withTransaction anymore ☺️

**Comment by itzomen** [comment]
Thanks
