### ISSUE TITLE
Fulfillment Provider/Service

### ISSUE THREAD

**Issue by chrisp-code** [adrien2p/medusa-extender#125]
**Is your feature request related to a problem? Please describe.**
I am trying to add a custom [Fulfillment Provider](https://docs.medusajs.com/advanced/backend/shipping/add-fulfillment-provider/) and have created the service, but it only gets registered as a service and not a fulfillment provider. When attempting to use the fulfillment provider on a region or shipping profile I get `Error: Fulfillment provider not found`.

I don't see any documentation and looking at the source code, I don't see any logic for registering the fulfillment service.

Is there a recommended solution?

**Describe the solution you'd like**
If a service is an `instanceof FulfillmentService` it should also get registered as a fulfillment provider, similar to [medusa's plugin loader](https://github.com/medusajs/medusa/blob/b78171b80cbeae4fb87ee3604cb40520ed397925/packages/medusa/src/loaders/plugins.ts#L382). I'm assuming something could be done similar to [entities.loader.ts](https://github.com/adrien2p/medusa-extender/blob/21eecf160aab05ab14981fa35c41fa0a28449728/src/loaders/entities.loader.ts#L60) to call `registerAdd`?

**Describe alternatives you've considered**
I attempted to manually register the provider after module loading in `main.ts` like:
```typescript
const medusa = await new Medusa(
    resolve(__dirname, '..'),
    expressInstance
).load([
    ...custom modules...
]);

medusa.registerAdd(
    'fulfillmentProviders',
    asFunction((cradle) => new MyCustomFulfillmentService(cradle, {}), {
        lifetime: 'SINGLETON',
    })
);

let fulfilProviders;
try {
    fulfilProviders = medusa.resolve('fulfillmentProviders');
} catch {
    fulfilProviders = [];
}
    
await medusa.resolve<FulfillmentProviderService>(
    'fulfillmentProviderService'
).registerInstalledProviders(
    fulfilProviders.map((p) => p.getIdentifier())
);

expressInstance.listen(PORT, () => {
    console.info(`Server successfully started on port ${PORT}`);
});
```

But I still get the `Error: Fulfillment provider not found` message. I wIll try a custom service overriding `FulfillmentProviderService` or create the fulfillment service as a local plugin to see if that fixes the issue in the meantime.

**Comment by adrien2p** [comment]
Hey there, at the moment for the specific plugins, strategies, providers, you can use the medusa way since it is something that can be a plugin. Even using the medusa way to do it, you will still be able to access you custom services through the container.

I ll add some decorators later for that 🤘

**Comment by chrisp-code** [comment]
So the Medusa way would be to create a local plugin or put the service in `src/services` as mentioned in their guide?

Sounds good, thank you! 🙏🏻

**Comment by adrien2p** [comment]
Both approach are allowed, i would probably choose to create a plugin so that it can be used in different projects. This is why as of now i don't really see a valid point to provide a way through the extender. Happy to ear your thoughts on that 😀

**Comment by haveamission** [comment]
Is this still best practices? I am looking for the best/easiest way to implement a custom TaxProvider

**Comment by chrisp-code** [comment]
@haveamission easiest is to put it in the `src/services` directory and build
