### ISSUE TITLE
Register Fulfillment (and other special) services with @Service annotation

### ISSUE THREAD

**Issue by dwene** [adrien2p/medusa-extender#128]
It would be nice to be able to register FulfillmentServiceProviders using the Medusa-Extender modules.

In the vanilla Medusa plugin setup, Medusa checks to see if the service is an instance of BaseFulfillmentService during startup to know to register that provider as a normal service or as a fulfillment provider. But when annotating that same service using Medusa-Extender, it doesn't use the same logic to check the base service type. All services are just registered as their name.

Seems like it wouldn't be too hard to clone the Medusa code that registers those services right?

**Comment by adrien2p** [comment]
Yes you are right, we can create specific decorators (the same way it works for the other ones) for them and load them in the right place with a loader 🤘 would you like to open a pr?
