### ISSUE TITLE
[BUG] Multi tenancy on default setup doesnt work

### ISSUE THREAD

**Issue by Inoir** [adrien2p/medusa-extender#131]
**Describe the bug**
Currently the multi tenancy on default setup of the project does not work. Mostly caused of the behaviour medusa is loading the configModule and strips off all custom props. Since the TenantService is using the resolved configModule from the container, there is no multi_tenancy config in the one provided in the tenant service.

Other point why its not working is the TenantService itself does not get registered anymore. I only got it working with own module and importing the service and middleware there. So seems something is wrong in the module, but couldnt figure out. ( Just looked into the code and seems same issue as in TenantService, module uses the configModule resolved from container, so no multi_tenancy options in there)

**To Reproduce**
1. Checkout new medusa-extender proj
2. Configure multi tenancy and use the tenant module
3. Try make a request to some tenant products (i.e list products)
4. Error is thrown cause either tenantService couldnt be resolved (first issue) or Error is thrown cause of multi_tenancy options not set in the configModule loaded in the TenantService

**Expected behavior**
Should work

**Screenshots**
<img width="700" alt="Screenshot 2022-09-30 at 13 59 08" src="https://user-images.githubusercontent.com/5294072/193264814-9a3a7769-4c4e-45f1-9b1f-2b23cdb4d92c.png">

**Package version:**
 medusa-extender: 1.7.6
 medusa: 1.4.1

**Comment by Inoir** [comment]
Maybe also a hint here => i opened a pull request, to get this working in medusa without loading the config over and over again: https://github.com/medusajs/medusa/pull/1896
Maybe also easier to understand why the multi_tenancy options are missing in the configModule from the container

**Comment by adrien2p** [comment]
Indeed, the config get in the module is from your config so that one contains it, but in the service it is resolved through the container. 

I did not marked it as experimental but as i explain to someone it is experimental. Let see once medusa will allow to have custom properties to be able to look deeper into it. 

About loading the module. How did you import it to get the service not registered ?

**Comment by Inoir** [comment]
Thanks for responding. Maybe should be more clearly in the docs, so people actually dont try to use it and only take it as guide how to do. Maybe also the custom props not supported in medusa should be pointed out. Took me a while to figure out whats wrong.

About the import: nothing special, only registered the module in the load function and enabled it in the config with some tenant settings. the middleware was registered but service not. since it was only for a test, i give up on this point.

**Comment by adrien2p** [comment]
Sorry for the miss understanding, just seen that the module was marked as experimental in the documentation. But just in case, I did add a disclaimer block to be sure :)
