### ISSUE TITLE
[BUG] new endpoint prefixed with /store by-passes even without auth header(cookie: connect.sid)

### ISSUE THREAD

**Issue by redhat125** [adrien2p/medusa-extender#136]
**Describe the bug**
On creating new endpoint prefixed with /store (/store/products/prod_01GD2JEGN6A7NBVWXCFE3Y2K4H/reviews), despite configuring **requireAuth** as **true** the api call without any type of authentication header (eg cookie: connect.sid) is still passing and executes the whole function where as just changing from /store to /admin (/admin/products/prod_01GD2JEGN6A7NBVWXCFE3Y2K4H/reviews) it works as expected and gives unauthorized (401) response. 

**To Reproduce**
1. create new endpoint prefixed with /store (or anything other than /admin), keep **requireAuth** as **true**
2. start the service, call from postman **without** any auth header eg
3. it'll still execute the request

**Expected behavior**
when any auth header eg (Cookie:connect.sid=s%3APtvXLoUjw3pG_KRKqlSgoH139byEOP9j.I58Wq7uslQe9KXWF8VpbeUv%2BAlS6fG4a8XaHCnUH8cY) isn't sent in the request for the endpoint that configured with **requireAuth** as **true**, system should respond with unauthorized. 
this works as expected when the endpoint is starting with /admin 

**Screenshots**
please notice the header in both the cases
/store
<img width="1258" alt="Screenshot 2022-10-13 at 1 01 21 AM" src="https://user-images.githubusercontent.com/9995578/195431538-a83cbe11-774f-483a-9861-416104700113.png">

/admin
<img width="1265" alt="Screenshot 2022-10-13 at 1 02 52 AM" src="https://user-images.githubusercontent.com/9995578/195431793-bb1e9a98-77e1-4756-a1a1-c5a0feed230f.png">

**Package version:**
 - Version [1.7.6]
 - "medusa-extender": "^1.7.6",

**Additional context**
along with router, its the same behavior with middleware as well

**Comment by adrien2p** [comment]
it is how medusa works, all store routes can be guarded by auth mechanisms to allow authentication, which is what it does when you set requireAuth, the route will use the medusa internal auth system. but the auth is not required in medusa core. For that you need to add a middleware to validate that the customer is authenticated by just checking if it is part of the request or return 401 otherwise.

**Comment by redhat125** [comment]
thank you so much @adrien2p for the clarification.
