### ISSUE TITLE
medusa develop command does not work with medusa-extender[BUG]

### ISSUE THREAD

**Issue by arkrozycki** [adrien2p/medusa-extender#145]
**Describe the bug**
Running the `medusa develop` command does not execute any modules from medusa-extender, including the example one that creates `/admin/custom-route`. If I execute `npm start` it works. However `npm start` method will not provide live reloading.

**To Reproduce**
1. Install vanilla medusa
2. Seed
3. Install vanilla medusa admin
4. Verify admin login
5. Install medusa-extender per docs.
6. Verify example module created
7. execute `medusa develop`
8. route to example extended module `/admin/custom-route` not working

You can even try changing the requiredAuth to false and it still does not work.

`main.ts` server start should print `Server successfully started on port`
<img width="607" alt="Screen Shot 2022-11-16 at 1 35 50 PM" src="https://user-images.githubusercontent.com/643157/202288741-b66d7118-6091-4a15-8238-89ce5ab551d0.png">

When you execute `medusa develop` you get `Server is ready on port`
<img width="448" alt="Screen Shot 2022-11-16 at 1 35 59 PM" src="https://user-images.githubusercontent.com/643157/202288976-fcaba3b3-a106-46d9-a752-b66c71d96210.png">

If you execute `npm start` it works
<img width="463" alt="Screen Shot 2022-11-16 at 1 36 22 PM" src="https://user-images.githubusercontent.com/643157/202289085-e0a0b62c-0170-439d-ae6b-4bd98ca55024.png">

If this is not a bug, it should be noted in documentation that `medusa develop` is not compatible with medusa-extender. Additionally, it would be nice to know how to get live reloading working with medusa-extender.

**Comment by adrien2p** [comment]
Thanks for that, as you mentioned it is note a bug and this is also why there is a start script in your package.json as well as an entry point file named main.ts which is used to run the server and al' that is part of the doc. If you want hot reloading you can use a simple nodemon command 🔥💪👍

**Comment by arkrozycki** [comment]
I'm fairly new to medusa and most if not all the documentation and articles reference the `medusa develop` command. I would suggest making a note of it in your documentation/site so that new comers do not assume it does not work. Which is where I was headed and about to discard medusa-extender as a dead project.

For what it's worth, I added the following command to my `package.json` file to handle reloads, might be helpful.

`"start:local": "nodemon -e ts --ignore node_modules/ --ignore dist/ -w src/ -x 'npm run build && NODE_ENV=development node ./dist/main.js'"`

Just run `npm run start:local` and you the server restarts on saves. So far it's working.

**Comment by adrien2p** [comment]
Thank you a lot for your feedback, the extender is a special package that require a minimum amount of knowledge on medusa before jumping straight in with the extender. The extender has its own cli to improve the dx with it and the init command populate the needed scripts to work with the extender along medusa itself. But, the medusa cli is only for medusa and the extender cli help your work with the extender and medusa together. Hope everything is more clear now and that you like it 😀
