### ISSUE TITLE
[BUG] Middleware not working as expected for Loggedin User

### ISSUE THREAD

**Issue by oakbani** [adrien2p/medusa-extender#151]
**Describe the bug**
I am following the marketplace tutorial using medusa extender. And I am unable to fetch user details in the middleware. The code is exactly how it's given in medusa-extender doc or in the tutorial. 

**To Reproduce**
1. Go to ' [This PR ](https://github.com/oakbani/medusa-bazar/pull/1/files#diff-bbca871006e420b1d55e467b7e9f915ffc1f3048b127ee707507f1cf7b7fd853)

**Expected behavior**
Should get user with user id in the context

**Screenshots**
<img width="990" alt="image" src="https://user-images.githubusercontent.com/14175871/209135951-17cfe932-9787-41ed-b617-2ac66ed8f9a6.png">
<img width="287" alt="image" src="https://user-images.githubusercontent.com/14175871/209136037-872262f7-94d6-47d0-8265-f7cbe6992c50.png">

**Package version:**
 - Trying with latest medusa

**Additional context**
None

**Comment by adrien2p** [comment]
Hey there, i ve updated the doc in the open pr, you have to target a domain. All is reserved for custom end points. Admin for admin end points and store for store endpoints. That way it is easier to manage knowing that you can specify multiple routes
