### ISSUE TITLE
[BUG] store routes requiredAuth does not work.

### ISSUE THREAD

**Issue by dwene** [adrien2p/medusa-extender#155]
**Describe the bug**

Using `requiredAuth` on the store routes doesn't seem to work anymore.

**To Reproduce**
1. create a /store/anything route using Medusa Extender
2. set the `requiredAuth` property to true.
3. Try to call the route unauthenticated, and notice it doesn't throw an error.

**Expected behavior**
It should return an Unauthorized response code.

**Screenshots**

**Package version:**
 - Medusa 1.7.2, Extender 1.7.8

**Additional context**

**Comment by adrien2p** [comment]
It has always been the case, the store auth middleware does not enforce the customer to be authenticated. I ve already answered the same type of issues. The requireAuth will only affect when the route will be registered, before or after the auth middleware in the core. To enforce it on the store route, you have to apply the https://github.com/medusajs/medusa/blob/master/packages/medusa/src/api/middlewares/require-customer-authentication.ts

On the other hand, I understand that I should change that. I ll create a pr to address that very soon 💪

**Comment by adrien2p** [comment]
for reference https://github.com/adrien2p/medusa-extender/pull/156

**Comment by adrien2p** [comment]
available in the next relrease
