### ISSUE TITLE
MetadataReader comprehensive error message

### ISSUE THREAD

**Issue by adrien2p** [adrien2p/medusa-extender#163]
When something that should not be present and that is not decorated is added to a module, an error is thrown with an error message that is not clear.

Instead, catch the error and display a comprehensive message such as class XXX is not decorated and should either be or should not be part of the module YYY

**Comment by juanzgc** [comment]
A potential addition:
Add a warning/error if a `.subscriber` is added to a Module. As subscribers are not to be in a Module.

**Comment by juanzgc** [comment]
@adrien2p Should we keep this issue still `open`?

**Comment by adrien2p** [comment]
What for?

**Comment by juanzgc** [comment]
Sorry didn't see the commit so was unsure if it had been merged or not 😇

**Comment by juanzgc** [comment]
Will reference it here: https://github.com/adrien2p/medusa-extender/commit/0522d0cd5209a7441628c320aa4123e942d9834d
