### ISSUE TITLE
DOC: Add use case for the extender

### ISSUE THREAD

**Issue by adrien2p** [adrien2p/medusa-extender#166]
A lot of people are using the extender for the wrong reason or the wrong way or do not know that medusa also allows some level of customization. Make it clear when to use the extender and the steps before jumping into using it.

**Comment by adrien2p** [comment]
Still need to do it, I was quite busy but the issue is not dead 😀

**Comment by agustif** [comment]
Hey adrien with all the new modularization added to the main repo, is extender still needed/recommended for some cases?

**Comment by adrien2p** [comment]
Everything is now doable in medusajs directly without requiring the extender ☺️
