### ISSUE TITLE
medusa-auth-plugin not working with 1.8.8 extender

### ISSUE THREAD

**Issue by Arsenalist** [adrien2p/medusa-extender#175]
**Describe the bug**
The callback from auth plugin is never handled and the admin callback function is never called. For example the following URL will just result in a failureUrl of the plugin being called. This worked fine in extender 1.8.2.

http://localhost:9000/admin/auth/auth0/cb?code=abc&state=def

**To Reproduce**
1. Configure auth0 in medusa-auth-plugin
2. Use extender 1.8.8
3. Validate successfully using auth0
4. failureUrl will be called instead of successUrl

**Expected behavior**
admin callback function is called after successful authentication

**Package version:**
 -  1.8.8

**Comment by adrien2p** [comment]
I don't see what the extender could do to generate that behaviour. Another company is using auth0 with the extender 1.8.8 and everything is working as expected. Are you sure that calling the cb manually with random values will work?

**Comment by Arsenalist** [comment]
I wasn't calling it with random values, but obfuscated them just to post publicly.

I will investigate more, but the only difference in the app breaking/not breaking is the extender version.

**Comment by adrien2p** [comment]
Sorry i thought that to test it you were manually calling the cb route. Can you share your config please

**Comment by adrien2p** [comment]
@Arsenalist do you have any more info?

**Comment by Arsenalist** [comment]
Sorry haven’t had time. I’ll close it and re-open when I do get a chance. For now I have downgraded to 1.8.2 and it work fine. 

I think the sequence of middleware execution changes had an impact but I haven’t looked deeply into it.

**Comment by adrien2p** [comment]
Got it, but there is no order of middleware that has changed. If it is required auth, the auth middleware is applied and then the handlers are called
