### ISSUE TITLE
[BUG] Unable to Intsall extender on latest Medusa

### ISSUE THREAD

**Issue by MuhammadRafay151** [adrien2p/medusa-extender#196]
**Describe the bug**
Unable to install medusa-extender on newly created medusa app (latest version)

**To Reproduce**
1. Create a new Medusa app.
2. Install Medusa extender.
3. See the error.

**Expected behavior**
I should be able to successfully install the medusa-extender on the latest Medusa app

**Screenshots**
<img width="656" alt="image" src="https://github.com/adrien2p/medusa-extender/assets/46870378/7f2761b6-ef8c-488e-ad73-ef4aa543a581">

**Package version:**
 - Version Latest

**Additional context**
N/A

**Comment by adrien2p** [comment]
As mentioned in the readme, this repo is deprecated ⚠️
