### ISSUE TITLE
[Feature] multi-tenancy design

### ISSUE THREAD

**Issue by adrien2p** [adrien2p/medusa-extender#50]
As a user, I would like to be able to run an instance of the app and being able to switch the database in use depending on the domain

**Comment by adrien2p** [comment]
Resolve by [PR](#46)

**Comment by SalahAdDin** [comment]
@adrien2p is this related to the multivendor feature?

**Comment by adrien2p** [comment]
Hey 👋 no its not, its a plugin I will export into the medusa-plugins repo. It just provide the multi tenancy design architecture for the users who need it. For example some users asked to manage multiple store with one instance of medusa and for each store a database is linked

**Comment by SalahAdDin** [comment]
Multi-vendor feature is still missing.

**Comment by adrien2p** [comment]
this package does not provide a multi-vendor feature, but it aims to help with this use case if needed as well as other use cases

**Comment by adrien2p** [comment]
The purpose of this project is to provides whats needed to customise medusa in the way you need it

**Comment by adrien2p** [comment]
@SalahAdDin you can have a look at this for a marketplace [step 1](https://github.com/shahednasser/medusa-marketplace-tutorial)

**Comment by SalahAdDin** [comment]
> @SalahAdDin you can have a look at this for a marketplace [step 1](https://github.com/shahednasser/medusa-marketplace-tutorial)

Ok, thank you very much, I will check it!
