### ISSUE TITLE
[BUG] medex init command generates faulty example.services.ts file

### ISSUE THREAD

**Issue by octalpixel** [adrien2p/medusa-extender#66]
**Describe the bug**
The service file created by the init command has an error while compiling. The "exampleServic" is not a variable but rather a string that has a typo. The string should be "exampleService".

**To Reproduce**
1. Create a new project with the init command using the cli
2. example.service.ts 
3. See error

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/30002284/159185505-8b123a8f-73da-464b-832d-dbb1db4a6e1a.png)

**Package version:**
 - 1.6

**Additional context**

**Comment by adrien2p** [comment]
Thanks for reporting @octalpixel 🚀 
here is the [PR](https://github.com/adrien2p/medusa-extender/pull/64) that fix it
