### ISSUE TITLE
[Feature]  Security enhancement for multi-tenancy

### ISSUE THREAD

**Issue by xc0d3rz** [adrien2p/medusa-extender#75]
Storing sensitive information like **database credentials** in plain text format on a database can lead to a disastrous chain of events.

I suggest to store them in `medusa-config.js`.

**Comment by adrien2p** [comment]
Hey 👋 completely agree on that, the only thing I am not agree is to put them in the medusa config.

With the approach you are proposing you need to re deploy your server each time you need to add a tenant. What about hashing them just like a password?

**Comment by adrien2p** [comment]
Thank you @xc0d3rz it is completely true, just asked you to do some changes and here we go 😀

**Comment by geek3000** [comment]
Hello, please i need help implementing multi tenancy. I have already configured the medusa-config.js file but it does not work

**Comment by adrien2p** [comment]
@geek3000 is that alright if we wait for @xc0d3rz to finalise this PR? it will be easier to use then

**Comment by geek3000** [comment]
@adrien2p ok thanks

**Comment by adrien2p** [comment]
@xc0d3rz just a follow up ☺️
