### ISSUE TITLE
[Bug] middlewares

### ISSUE THREAD

**Issue by adrien2p** [adrien2p/medusa-extender#84]
Middleware should handle parametric routes

**Comment by adrien2p** [comment]
Work around at the moment, use the handlers from the router

**Comment by anup-a** [comment]
Hi @adrien2p 

In apply-middleware.ts (line 61)
```
const shouldHandle = middleware.routes.some((route) => {
			return (
				(route.method === 'all' || req.method.toLowerCase() === route.method.toLowerCase()) &&
				(route.path === '*' || req.originalUrl === route.path)
			);
		});
```
Instead of directly matching router and url with === operator, we could use `match` utility from `path-to-regexp`.

I believe this could solve the issue https://github.com/pillarjs/path-to-regexp.

**Comment by adrien2p** [comment]
Seams to be very nice thanks ☺️, before trying that, can we try to just apply the middleware the same way the router does? If that does not work (just in case 😎) then we can use that kind of package.

**Comment by anup-a** [comment]
Yes that is clever 👍 and would be much better I guess.

Also I checked we could pass an array of routes to app.use.
Something like this could work.
In apply-middleware.ts line 57,
```
app.use(middleware.routes.route.map(r => r.route), callback)
```
But we will need to have to make a method check in callback.

**Comment by adrien2p** [comment]
Would you want to do the PR and Ill review it when your done? It would be very nice 😊

**Comment by anup-a** [comment]
Sure I would love to.
I'm just wondering how will I test this feature🤔

**Comment by adrien2p** [comment]
When the integration will be added it will be much easier, in the meantime for that one you can create a sandboxed env and tests it that way. Then, Ill add those kind of tests in the integration suite ☺️

**Comment by anup-a** [comment]
@adrien2p
I will have to create a new medusa project which uses my local medusa-extender, right?
 Might be a silly question, but how do I create the sandboxed env?

**Comment by adrien2p** [comment]
Ahah no problem. I will push the integration soon. Which leans that you will be ab'e to test it

**Comment by anup-a** [comment]
Sure, meanwhile i will create the PR.
