### ISSUE TITLE
Proper Documentation request for Multitenancy feature

### ISSUE THREAD

**Issue by vedraiyani** [adrien2p/medusa-extender#91]
**Is your feature request related to a problem? Please describe.**
I followed the doc for multitenancy where it's mentioned to set up the config but nothing is said about how we can configure the tenant for the store. I could also see that `Multi-tenant 1` is mentioned so how to configure db for each tenant?

**Comment by adrien2p** [comment]
Yes, you are right. I will improve that as well as the way it work. At the moment, you have to out the different db into the database in the multi tenant table. But they are registered in clear. Asap i will move that to be fully in the config so that way you can hide the creds in the env instead.

**Comment by adrien2p** [comment]
#93 will change the way the module work, the documentation update will be part of it. Everything will be part of the next release 👍

**Comment by adrien2p** [comment]
@vedraiyani just wanted to know a bit more about the usage for the multi tenancy that you are looking for. Could you tell me a bit more about your use case before merging the branch and updating the doc.

At the moment, you have the capabilities of different multi tenancy approach with the extender.

**Comment by adrien2p** [comment]
@vedraiyani just wanted to know a bit more about the usage for the multi tenancy that you are looking for. Could you tell me a bit more about your use case before merging the branch and updating the doc.

At the moment, you have the capabilities of different multi tenancy approach with the extender.

**Comment by vedraiyani** [comment]
@adrien2p I was thinking of providing multiple tenants(e.g. test, production,...) of the same customer under the same server or may be multiple stores under the same server
